/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import Users.FileOperation;
import Users.LoginPage;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CustomerStatus extends javax.swing.JFrame {

    /**
     * Creates new form CustomerStatus
     */
    public CustomerStatus() {
        initComponents();
        this.setLocationRelativeTo(null);
        generateTable();
    }
    
     public void generateTable() {
        String[] columns = {"Issue ID","Reservation ID","Customer Email", "Customer Name", "Main Issues", "Status", "Remarks"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        FileOperation file = new FileOperation();
        file.setFile("resources/database/customerFeedback.txt"); 
        file.checkFilePath();
        file.retrieveData();

        ArrayList<String> statusRecords = file.getRetrievedData();
        for (String record : statusRecords) {
            String[] details = record.split(",");

                String issueID = details[0];
                String reservationID = details[1];
                String customerEmail = details[2];
                String customerName = details[3];
                String mainIssue = details[4];
                String status = details[5];
                String remarks = details[6];

                model.addRow(new Object[]{issueID, reservationID, customerEmail, customerName, mainIssue, status, remarks});
        }


        statusTable.setModel(model);
    }
     
    private ArrayList<String> collectAllData() {
        ArrayList<String> allData = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) statusTable.getModel();

        for (int row = 0; row < model.getRowCount(); row++) {
            StringBuilder record = new StringBuilder();

            for (int col = 0; col < model.getColumnCount(); col++) {
                record.append(model.getValueAt(row, col)).append(",");
            }

            if (record.length() > 0) {
                record.setLength(record.length() - 1); // Remove trailing comma
            }
            allData.add(record.toString());
        }

        return allData;
    }

    private void updateSelectedRow() {
        DefaultTableModel model = (DefaultTableModel) statusTable.getModel();
        int selectedRow = statusTable.getSelectedRow();

        if (selectedRow != -1) {
            String IssueID = issuefield.getText(); 
            String ReservationID = reservationIdField.getText();
            String Email = emailField.getText();
            String Name = namefield.getText();       
            String Status = (String) statuscombo.getSelectedItem();
            String MainIssue = mainissue.getText();
            String Remarks = remarkfield.getText();

            model.setValueAt(IssueID, selectedRow, 0);
            model.setValueAt(ReservationID, selectedRow, 1);
            model.setValueAt(Email, selectedRow, 2);
            model.setValueAt(Name, selectedRow, 3);
            model.setValueAt(MainIssue, selectedRow, 4);
            model.setValueAt(Status, selectedRow, 5);
            model.setValueAt(Remarks, selectedRow, 6);
        } else {
            JOptionPane.showMessageDialog(null, "No row selected to update.");
        }
    }

    public void saveAllChanges() {
        int selectedRow = statusTable.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "No row selected to save changes.");
            return;
        } 


        updateSelectedRow(); 
        ArrayList<String> allData = collectAllData(); 

        FileOperation fileHandler = new FileOperation();
        fileHandler.setFile("resources/database/customerFeedback.txt"); 

        fileHandler.updateData(allData); 
        JOptionPane.showMessageDialog(null, "Status updated successfully!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        leftMenu12 = new javax.swing.JPanel();
        homeLink = new javax.swing.JLabel();
        salesManagmentLink = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        Homebtn12 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        logoutLink = new javax.swing.JLabel();
        taskAssignmentLink = new javax.swing.JLabel();
        jLabel219 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        rightMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();
        jLabel36 = new javax.swing.JLabel();
        issuefield = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        statuscombo = new javax.swing.JComboBox<>();
        remarkfield = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        mainissue = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        reservationIdField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(248, 246, 240));
        background.setPreferredSize(new java.awt.Dimension(980, 650));

        leftMenu12.setBackground(new java.awt.Color(172, 225, 199));
        leftMenu12.setPreferredSize(new java.awt.Dimension(220, 620));

        homeLink.setText("Home Page");
        homeLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLinkMouseClicked(evt);
            }
        });

        salesManagmentLink.setText("Sales Management");
        salesManagmentLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salesManagmentLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesManagmentLinkMouseClicked(evt);
            }
        });

        jLabel206.setText("Customer Issues");
        jLabel206.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator13.setPreferredSize(new java.awt.Dimension(65, 10));

        Homebtn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/home.png"))); // NOI18N
        Homebtn12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Homebtn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Homebtn12MouseClicked(evt);
            }
        });

        jLabel208.setBackground(new java.awt.Color(153, 153, 153));
        jLabel208.setForeground(new java.awt.Color(102, 102, 102));
        jLabel208.setText("General");

        jLabel209.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/rent.png"))); // NOI18N
        jLabel209.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel210.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/check-up.png"))); // NOI18N
        jLabel210.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel212.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/logout.png"))); // NOI18N
        jLabel212.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        logoutLink.setText("Log Out");
        logoutLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLinkMouseClicked(evt);
            }
        });

        taskAssignmentLink.setText("Scheduler Assign");
        taskAssignmentLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taskAssignmentLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taskAssignmentLinkMouseClicked(evt);
            }
        });

        jLabel219.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/refund.png"))); // NOI18N
        jLabel219.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel207.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel207.setText("CUSTOMER");

        jLabel220.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel220.setText("STATUS");

        javax.swing.GroupLayout leftMenu12Layout = new javax.swing.GroupLayout(leftMenu12);
        leftMenu12.setLayout(leftMenu12Layout);
        leftMenu12Layout.setHorizontalGroup(
            leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenu12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel207)
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jLabel219)
                        .addGap(18, 18, 18)
                        .addComponent(taskAssignmentLink))
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(Homebtn12)
                        .addGap(18, 18, 18)
                        .addComponent(homeLink))
                    .addComponent(jLabel208)
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jLabel209)
                        .addGap(18, 18, 18)
                        .addComponent(salesManagmentLink))
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jLabel210)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel206))
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jLabel212)
                        .addGap(18, 18, 18)
                        .addComponent(logoutLink))
                    .addComponent(jLabel220))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        leftMenu12Layout.setVerticalGroup(
            leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenu12Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel207)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel220)
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(Homebtn12))
                    .addComponent(homeLink))
                .addGap(18, 18, 18)
                .addComponent(jLabel208)
                .addGap(13, 13, 13)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel209)
                    .addComponent(salesManagmentLink))
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel210)
                    .addComponent(jLabel206))
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel219)
                    .addComponent(taskAssignmentLink))
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel212)
                    .addComponent(logoutLink))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightMenu.setBackground(new java.awt.Color(248, 246, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Current Customer Status");

        statusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        statusTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(statusTable);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel36.setText("Issue ID");

        issuefield.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        issuefield.setEnabled(false);
        issuefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuefieldActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel39.setText("Status");

        statuscombo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        statuscombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In progress", "Done", "Closed", "Cancelled" }));

        remarkfield.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel38.setText("Remarks");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel37.setText("Name");

        namefield.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        namefield.setEnabled(false);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel40.setText("Main Issue");

        mainissue.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Email");

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel3.setText("Reserve ID");

        javax.swing.GroupLayout rightMenuLayout = new javax.swing.GroupLayout(rightMenu);
        rightMenu.setLayout(rightMenuLayout);
        rightMenuLayout.setHorizontalGroup(
            rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightMenuLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightMenuLayout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(106, 106, 106))
                        .addGroup(rightMenuLayout.createSequentialGroup()
                            .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel37)
                                .addComponent(jLabel36)
                                .addComponent(jLabel1))
                            .addGap(352, 352, 352))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightMenuLayout.createSequentialGroup()
                            .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rightMenuLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(reservationIdField)
                                        .addGroup(rightMenuLayout.createSequentialGroup()
                                            .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(rightMenuLayout.createSequentialGroup()
                                                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel39))
                                                .addGroup(rightMenuLayout.createSequentialGroup()
                                                    .addComponent(issuefield, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(72, 72, 72)
                                                    .addComponent(jLabel2)))
                                            .addGap(29, 29, 29)
                                            .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(emailField)
                                                .addComponent(statuscombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGap(68, 68, 68)))
                    .addGroup(rightMenuLayout.createSequentialGroup()
                        .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mainissue, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                            .addComponent(remarkfield))
                        .addContainerGap())))
        );
        rightMenuLayout.setVerticalGroup(
            rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightMenuLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(reservationIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issuefield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel2)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel39)
                    .addComponent(statuscombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainissue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(remarkfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        emailField.setEnabled(false);
        reservationIdField.setEnabled(false);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(leftMenu12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftMenu12, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addComponent(rightMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Homebtn12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Homebtn12MouseClicked
        ManagerDashboard manage = new ManagerDashboard();
        manage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Homebtn12MouseClicked

    private void statusTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) statusTable.getModel();
        int selectedRow = statusTable.getSelectedRow();

        if (selectedRow >= 0) {
            String IssueID = model.getValueAt(selectedRow, 0).toString();
            String ReservationID = model.getValueAt(selectedRow, 1).toString();
            String Email = model.getValueAt(selectedRow, 2).toString();
            String Name = model.getValueAt(selectedRow, 3).toString();
            String MainIssue = model.getValueAt(selectedRow, 4).toString();
            String Status = model.getValueAt(selectedRow, 5).toString();
            String Remarks = model.getValueAt(selectedRow, 6).toString();

            issuefield.setText(IssueID);
            reservationIdField.setText(ReservationID);
            emailField.setText(Email);
            namefield.setText(Name);
            statuscombo.setSelectedItem(Status);
            mainissue.setText(MainIssue);
            remarkfield.setText(Remarks);

        } else {
            System.out.println("No row selected.");
        }
    }//GEN-LAST:event_statusTableMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        collectAllData();
        saveAllChanges();
    }//GEN-LAST:event_jButton1MouseClicked

    private void issuefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issuefieldActionPerformed

    private void homeLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLinkMouseClicked
       ManagerDashboard dashboard = new ManagerDashboard();
       dashboard.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_homeLinkMouseClicked

    private void salesManagmentLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesManagmentLinkMouseClicked
        SalesManagement sales = new SalesManagement();
        sales.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salesManagmentLinkMouseClicked

    private void taskAssignmentLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskAssignmentLinkMouseClicked
        SchedulerAssign sa = new SchedulerAssign();
        sa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_taskAssignmentLinkMouseClicked

    private void logoutLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLinkMouseClicked

        LoginPage login = new LoginPage();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Homebtn12;
    private javax.swing.JPanel background;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel homeLink;
    private javax.swing.JTextField issuefield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JPanel leftMenu12;
    private javax.swing.JLabel logoutLink;
    private javax.swing.JTextField mainissue;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField remarkfield;
    private javax.swing.JTextField reservationIdField;
    private javax.swing.JPanel rightMenu;
    private javax.swing.JLabel salesManagmentLink;
    private javax.swing.JTable statusTable;
    private javax.swing.JComboBox<String> statuscombo;
    private javax.swing.JLabel taskAssignmentLink;
    // End of variables declaration//GEN-END:variables
}
