/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import Users.FileOperation;
import Users.LoginPage;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PriceCalculation extends javax.swing.JFrame {

    /**
     * Creates new form PriceCalculation
     */
    public PriceCalculation() {
        initComponents();
        this.setLocationRelativeTo(null);
        generateTable();
    }
    
    public void generateTable() {
    String columns[] = {"Reservation ID", "Hall ID", "Reservation Date", "Starting Time", "Duration", "Ending Time", "Total Price"};
    DefaultTableModel model = new DefaultTableModel(columns, 0);

    FileOperation file = new FileOperation();
    file.setFile("resources/database/reservation.txt");
    file.checkFilePath();
    file.retrieveData();

    ArrayList<String> reservationRecords = file.getRetrievedData();
    
    SimpleDateFormat inputFormat = new SimpleDateFormat("dd MMMM yyyy");
    SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd/MM/yyyy");
    
      Map<String, Double> hallPrices = Map.of(
        "H1", 300.00,
        "H2", 100.00,
        "H3", 50.00
    );

    for (String record : reservationRecords) {
        String[] details = record.split(",");
        String reservationID = details[0];
        String hallID = details[1];
        String reservationDateStr = details[2];
        String startingTime = details[3];
        String durationStr = details[4];

        String formattedReservationDate = "";
        try {
            Date date = inputFormat.parse(reservationDateStr);
            formattedReservationDate = outputDateFormat.format(date);
        } catch (ParseException e) {
            e.printStackTrace();
            formattedReservationDate = reservationDateStr; 
        }

         double startingTimeDouble = Double.parseDouble(startingTime);
        double durationDouble = Double.parseDouble(durationStr);
        double endingTimeDouble = startingTimeDouble + durationDouble;
        String endingTime = String.format("%.1f", endingTimeDouble);
        
        // Calculate total price
        double pricePerHour = hallPrices.getOrDefault(hallID, 0.0);
        double totalPrice = durationDouble * pricePerHour;
        
        model.addRow(new Object[]{
            reservationID, 
            hallID, 
            formattedReservationDate, 
            startingTime, 
            durationStr, 
            endingTime, 
            String.format("%.2f", totalPrice) // Total Price
        });
    }

    // Set the model to the table
    SalesTable.setModel(model);
    }
    
    private String formatTime(double time) {
        int hours = (int) time;
        int minutes = (int) ((time - hours) * 60);
        return String.format("%02d%02d", hours, minutes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        leftMenu12 = new javax.swing.JPanel();
        homeLink = new javax.swing.JLabel();
        smLink = new javax.swing.JLabel();
        csLink = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        Homebtn12 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        logoutLink = new javax.swing.JLabel();
        taskLink = new javax.swing.JLabel();
        jLabel219 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SalesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(248, 246, 240));
        jPanel2.setMinimumSize(new java.awt.Dimension(980, 620));
        jPanel2.setPreferredSize(new java.awt.Dimension(980, 620));

        leftMenu12.setBackground(new java.awt.Color(172, 225, 199));
        leftMenu12.setPreferredSize(new java.awt.Dimension(220, 620));

        homeLink.setText("Home Page");
        homeLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLinkMouseClicked(evt);
            }
        });

        smLink.setText("Sales Management");
        smLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        smLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smLinkMouseClicked(evt);
            }
        });

        csLink.setText("Customer Issues");
        csLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        csLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csLinkMouseClicked(evt);
            }
        });

        jSeparator13.setPreferredSize(new java.awt.Dimension(65, 10));

        Homebtn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/home.png"))); // NOI18N
        Homebtn12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Homebtn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Homebtn12MouseClicked(evt);
            }
        });

        jLabel208.setBackground(new java.awt.Color(153, 153, 153));
        jLabel208.setForeground(new java.awt.Color(102, 102, 102));
        jLabel208.setText("General");

        jLabel209.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/rent.png"))); // NOI18N
        jLabel209.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel210.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/check-up.png"))); // NOI18N
        jLabel210.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel212.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/logout.png"))); // NOI18N
        jLabel212.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        logoutLink.setText("Log Out");
        logoutLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLinkMouseClicked(evt);
            }
        });

        taskLink.setText("Scheduler Assign");
        taskLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taskLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taskLinkMouseClicked(evt);
            }
        });

        jLabel219.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/refund.png"))); // NOI18N
        jLabel219.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel207.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel207.setText("SALES");

        jLabel220.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel220.setText("CALCULATION");

        javax.swing.GroupLayout leftMenu12Layout = new javax.swing.GroupLayout(leftMenu12);
        leftMenu12.setLayout(leftMenu12Layout);
        leftMenu12Layout.setHorizontalGroup(
            leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenu12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jLabel212)
                        .addGap(18, 18, 18)
                        .addComponent(logoutLink))
                    .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel207)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(leftMenu12Layout.createSequentialGroup()
                                .addComponent(Homebtn12)
                                .addGap(18, 18, 18)
                                .addComponent(homeLink))
                            .addComponent(jLabel208)
                            .addGroup(leftMenu12Layout.createSequentialGroup()
                                .addComponent(jLabel209)
                                .addGap(18, 18, 18)
                                .addComponent(smLink))
                            .addGroup(leftMenu12Layout.createSequentialGroup()
                                .addComponent(jLabel210)
                                .addGap(18, 18, 18)
                                .addComponent(csLink))
                            .addComponent(jLabel220))
                        .addGroup(leftMenu12Layout.createSequentialGroup()
                            .addComponent(jLabel219)
                            .addGap(18, 18, 18)
                            .addComponent(taskLink)
                            .addGap(36, 36, 36))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        leftMenu12Layout.setVerticalGroup(
            leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenu12Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel207)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel220)
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(Homebtn12))
                    .addComponent(homeLink))
                .addGap(18, 18, 18)
                .addComponent(jLabel208)
                .addGap(13, 13, 13)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel209)
                    .addComponent(smLink))
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel210)
                    .addComponent(csLink))
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel219)
                    .addComponent(taskLink))
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel212)
                    .addComponent(logoutLink))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(248, 246, 240));

        SalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(SalesTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Checking the Total Sales Made by :");

        jButton1.setText("Weekly");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Monthly");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Yearly");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(41, 41, 41)
                                .addComponent(jButton2)
                                .addGap(38, 38, 38)
                                .addComponent(jButton3))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(leftMenu12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftMenu12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Homebtn12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Homebtn12MouseClicked
        ManagerDashboard manage = new ManagerDashboard();
        manage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Homebtn12MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        calculateWeeklyTotals();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        calculateMonthlyTotals();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        calculateYearlyTotals();
    }//GEN-LAST:event_jButton3MouseClicked

    private void homeLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLinkMouseClicked
        ManagerDashboard dashboard = new ManagerDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeLinkMouseClicked

    private void smLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smLinkMouseClicked
        SalesManagement sales = new SalesManagement();
        sales.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smLinkMouseClicked

    private void csLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csLinkMouseClicked
        CustomerStatus cs = new CustomerStatus();
        cs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_csLinkMouseClicked

    private void taskLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskLinkMouseClicked
        SchedulerAssign sa = new SchedulerAssign();
        sa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_taskLinkMouseClicked

    private void logoutLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLinkMouseClicked
        LoginPage login = new LoginPage();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLinkMouseClicked
    
    private void calculateWeeklyTotals() {
        DefaultTableModel model = (DefaultTableModel) SalesTable.getModel();
        int rowCount = model.getRowCount();

        Map<String, Double> weeklyTotals = new HashMap<>();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        for (int i = 0; i < rowCount; i++) {
            String reservationDateStr = (String) model.getValueAt(i, 2); // Column index 2 for reservation date
            String totalPriceStr = (String) model.getValueAt(i, 6); // Column index 6 for total price

            double totalPrice;
            try {
                totalPrice = Double.parseDouble(totalPriceStr);
            } catch (NumberFormatException e) {
                e.printStackTrace();
                continue; 
            }

            try {
                Date reservationDate = dateFormat.parse(reservationDateStr);
                Calendar cal = Calendar.getInstance();
                cal.setTime(reservationDate);

                int weekOfMonth = cal.get(Calendar.WEEK_OF_MONTH);
                int month = cal.get(Calendar.MONTH) + 1; 
                String monthName = new SimpleDateFormat("MMMM").format(reservationDate);
                String weekKey = monthName + " Week " + weekOfMonth;

                weeklyTotals.put(weekKey, weeklyTotals.getOrDefault(weekKey, 0.0) + totalPrice);

            } catch (ParseException e) {
                e.printStackTrace();
            }
        }

        StringBuilder result = new StringBuilder("Weekly Totals:\n");
        for (Map.Entry<String, Double> entry : weeklyTotals.entrySet()) {
            result.append(entry.getKey()).append(": RM ").append(entry.getValue()).append("\n");
        }

        JOptionPane.showMessageDialog(null, result.toString());
    }

    private void calculateMonthlyTotals() {
        DefaultTableModel model = (DefaultTableModel) SalesTable.getModel();
        int rowCount = model.getRowCount();

        Map<String, Double> monthlyTotals = new HashMap<>();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        for (int i = 0; i < rowCount; i++) {
            String reservationDateStr = (String) model.getValueAt(i, 2); // Column index 2 for reservation date
            String totalPriceStr = (String) model.getValueAt(i, 6); // Column index 6 for total price

            double totalPrice;
            try {
                totalPrice = Double.parseDouble(totalPriceStr);
            } catch (NumberFormatException e) {
                e.printStackTrace();
                continue; // Skip this row if there is a parsing error
            }

            try {
                Date reservationDate = dateFormat.parse(reservationDateStr);
                Calendar cal = Calendar.getInstance();
                cal.setTime(reservationDate);

                int month = cal.get(Calendar.MONTH) + 1; // Calendar.MONTH is zero-based
                int year = cal.get(Calendar.YEAR);
                String monthKey = new SimpleDateFormat("MMMM").format(reservationDate) + " " + year;

                monthlyTotals.put(monthKey, monthlyTotals.getOrDefault(monthKey, 0.0) + totalPrice);

            } catch (ParseException e) {
                e.printStackTrace();
            }
        }

        StringBuilder result = new StringBuilder("Monthly Totals:\n");
        for (Map.Entry<String, Double> entry : monthlyTotals.entrySet()) {
            result.append(entry.getKey()).append(": RM ").append(entry.getValue()).append("\n");
        }

        JOptionPane.showMessageDialog(null, result.toString());
    }

    private void calculateYearlyTotals() {
        DefaultTableModel model = (DefaultTableModel) SalesTable.getModel();
        int rowCount = model.getRowCount();

        Map<String, Double> yearlyTotals = new HashMap<>();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        for (int i = 0; i < rowCount; i++) {
            String reservationDateStr = (String) model.getValueAt(i, 2); // Column index 2 for reservation date
            String totalPriceStr = (String) model.getValueAt(i, 6); // Column index 6 for total price

            double totalPrice;
            try {
                totalPrice = Double.parseDouble(totalPriceStr);
            } catch (NumberFormatException e) {
                e.printStackTrace();
                continue; // Skip this row if there is a parsing error
            }

            try {
                Date reservationDate = dateFormat.parse(reservationDateStr);
                Calendar cal = Calendar.getInstance();
                cal.setTime(reservationDate);

                int year = cal.get(Calendar.YEAR);
                String yearKey = String.valueOf(year);

                yearlyTotals.put(yearKey, yearlyTotals.getOrDefault(yearKey, 0.0) + totalPrice);

            } catch (ParseException e) {
                e.printStackTrace();
            }
        }

        StringBuilder result = new StringBuilder("Yearly Totals:\n");
        for (Map.Entry<String, Double> entry : yearlyTotals.entrySet()) {
            result.append(entry.getKey()).append(": RM ").append(entry.getValue()).append("\n");
        }

        JOptionPane.showMessageDialog(null, result.toString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PriceCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PriceCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PriceCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PriceCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PriceCalculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Homebtn12;
    private javax.swing.JTable SalesTable;
    private javax.swing.JLabel csLink;
    private javax.swing.JLabel homeLink;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JPanel leftMenu12;
    private javax.swing.JLabel logoutLink;
    private javax.swing.JLabel smLink;
    private javax.swing.JLabel taskLink;
    // End of variables declaration//GEN-END:variables
}
