/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import Users.FileOperation;
import Users.LoginPage;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class SalesManagement extends javax.swing.JFrame {

    /**
     * Creates new form SalesManagementForm
     */
    public SalesManagement() {
        initComponents();
        this.setLocationRelativeTo(null);
        generateTable();
    }
    
    public void generateTable() {
    String columns[] = {"Reservation ID", "Hall ID", "Reservation Date", "Starting Time", "Duration", "Ending Time", "Total Price"};
    DefaultTableModel model = new DefaultTableModel(columns, 0);

    FileOperation file = new FileOperation();
    file.setFile("resources/database/reservation.txt");
    file.checkFilePath();
    file.retrieveData();

    ArrayList<String> reservationRecords = file.getRetrievedData();
    
    SimpleDateFormat inputFormat = new SimpleDateFormat("dd MMMM yyyy");
    SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd/MM/yyyy");
    
      Map<String, Double> hallPrices = Map.of(
        "H1", 300.00,
        "H2", 100.00,
        "H3", 50.00
    );

    for (String record : reservationRecords) {
        String[] details = record.split(",");
        String reservationID = details[0];
        String hallID = details[1];
        String reservationDateStr = details[2];
        String startingTime = details[3];
        String durationStr = details[4];

        String formattedReservationDate = "";
        try {
            Date date = inputFormat.parse(reservationDateStr);
            formattedReservationDate = outputDateFormat.format(date);
        } catch (ParseException e) {
            e.printStackTrace();
            formattedReservationDate = reservationDateStr; 
        }

         double startingTimeDouble = Double.parseDouble(startingTime);
        double durationDouble = Double.parseDouble(durationStr);
        double endingTimeDouble = startingTimeDouble + durationDouble;
        String endingTime = String.format("%.1f", endingTimeDouble);
        
        // Calculate total price
        double pricePerHour = hallPrices.getOrDefault(hallID, 0.0);
        double totalPrice = durationDouble * pricePerHour;
        
        model.addRow(new Object[]{
            reservationID, 
            hallID, 
            formattedReservationDate, 
            startingTime, 
            durationStr, 
            endingTime, 
            String.format("%.2f", totalPrice) // Total Price
        });
    }

    // Set the model to the table
    SalesTable.setModel(model);
    }
    
    private String formatTime(double time) {
    int hours = (int) time;
    int minutes = (int) ((time - hours) * 60);
    return String.format("%02d%02d", hours, minutes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundf = new javax.swing.JPanel();
        leftMenu12 = new javax.swing.JPanel();
        homeLink = new javax.swing.JLabel();
        smLink = new javax.swing.JLabel();
        issueLink = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        Homebtn12 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        logoutLink = new javax.swing.JLabel();
        taskLink = new javax.swing.JLabel();
        jLabel219 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        rightMenu = new javax.swing.JPanel();
        jLabel221 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SalesTable = new javax.swing.JTable();
        calculationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundf.setBackground(new java.awt.Color(248, 246, 240));

        leftMenu12.setBackground(new java.awt.Color(172, 225, 199));
        leftMenu12.setPreferredSize(new java.awt.Dimension(220, 620));

        homeLink.setText("Home Page");
        homeLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLinkMouseClicked(evt);
            }
        });

        smLink.setText("Sales Management");
        smLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        issueLink.setText("Customer Issues");
        issueLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        issueLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueLinkMouseClicked(evt);
            }
        });

        jSeparator13.setPreferredSize(new java.awt.Dimension(65, 10));

        Homebtn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/home.png"))); // NOI18N
        Homebtn12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Homebtn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Homebtn12MouseClicked(evt);
            }
        });

        jLabel208.setBackground(new java.awt.Color(153, 153, 153));
        jLabel208.setForeground(new java.awt.Color(102, 102, 102));
        jLabel208.setText("General");

        jLabel209.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/rent.png"))); // NOI18N
        jLabel209.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel210.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/check-up.png"))); // NOI18N
        jLabel210.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel212.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/logout.png"))); // NOI18N
        jLabel212.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        logoutLink.setText("Log Out");
        logoutLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLinkMouseClicked(evt);
            }
        });

        taskLink.setText("Scheduler Assign");
        taskLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taskLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taskLinkMouseClicked(evt);
            }
        });

        jLabel219.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/refund.png"))); // NOI18N
        jLabel219.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel207.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel207.setText("SALES");

        jLabel220.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel220.setText("MANAGEMENT");

        javax.swing.GroupLayout leftMenu12Layout = new javax.swing.GroupLayout(leftMenu12);
        leftMenu12.setLayout(leftMenu12Layout);
        leftMenu12Layout.setHorizontalGroup(
            leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenu12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel207)
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jLabel219)
                        .addGap(18, 18, 18)
                        .addComponent(taskLink))
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(Homebtn12)
                        .addGap(18, 18, 18)
                        .addComponent(homeLink))
                    .addComponent(jLabel208)
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jLabel209)
                        .addGap(18, 18, 18)
                        .addComponent(smLink))
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jLabel210)
                        .addGap(18, 18, 18)
                        .addComponent(issueLink))
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jLabel212)
                        .addGap(18, 18, 18)
                        .addComponent(logoutLink))
                    .addComponent(jLabel220))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        leftMenu12Layout.setVerticalGroup(
            leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenu12Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel207)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel220)
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leftMenu12Layout.createSequentialGroup()
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(Homebtn12))
                    .addComponent(homeLink))
                .addGap(18, 18, 18)
                .addComponent(jLabel208)
                .addGap(13, 13, 13)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel209)
                    .addComponent(smLink))
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel210)
                    .addComponent(issueLink))
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel219)
                    .addComponent(taskLink))
                .addGap(18, 18, 18)
                .addGroup(leftMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel212)
                    .addComponent(logoutLink))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        rightMenu.setBackground(new java.awt.Color(248, 246, 240));

        jLabel221.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel221.setText("Search and Filter Sales");

        searchBar.setToolTipText("Search Query here");

        searchButton.setText("Search");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        SalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(SalesTable);

        calculationButton.setText("Calculate Price");
        calculationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculationButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rightMenuLayout = new javax.swing.GroupLayout(rightMenu);
        rightMenu.setLayout(rightMenuLayout);
        rightMenuLayout.setHorizontalGroup(
            rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculationButton))
                .addGap(45, 45, 45))
            .addGroup(rightMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel221)
                .addContainerGap(483, Short.MAX_VALUE))
            .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightMenuLayout.createSequentialGroup()
                    .addContainerGap(24, Short.MAX_VALUE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(148, 148, 148))
                .addGroup(rightMenuLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );
        rightMenuLayout.setVerticalGroup(
            rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightMenuLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel221, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calculationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightMenuLayout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(137, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout backgroundfLayout = new javax.swing.GroupLayout(backgroundf);
        backgroundf.setLayout(backgroundfLayout);
        backgroundfLayout.setHorizontalGroup(
            backgroundfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundfLayout.createSequentialGroup()
                .addComponent(leftMenu12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backgroundfLayout.setVerticalGroup(
            backgroundfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundfLayout.createSequentialGroup()
                .addGroup(backgroundfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rightMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftMenu12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Homebtn12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Homebtn12MouseClicked
        ManagerDashboard manage = new ManagerDashboard();
        manage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Homebtn12MouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        String searchText = searchBar.getText().trim();
        if (searchText.isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) SalesTable.getModel();
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
            SalesTable.setRowSorter(sorter);
        } else {
            DefaultTableModel model = (DefaultTableModel) SalesTable.getModel();
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
            SalesTable.setRowSorter(sorter);
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
        }
    }//GEN-LAST:event_searchButtonMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void calculationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculationButtonMouseClicked
        PriceCalculation price = new PriceCalculation();
        price.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calculationButtonMouseClicked

    private void homeLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLinkMouseClicked
        ManagerDashboard dashboard = new ManagerDashboard();
       dashboard.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_homeLinkMouseClicked

    private void issueLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueLinkMouseClicked
        CustomerStatus cs = new CustomerStatus();
        cs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_issueLinkMouseClicked

    private void taskLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskLinkMouseClicked
        SchedulerAssign sa = new SchedulerAssign();
        sa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_taskLinkMouseClicked

    private void logoutLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLinkMouseClicked
        LoginPage login = new LoginPage();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Homebtn12;
    private javax.swing.JTable SalesTable;
    private javax.swing.JPanel backgroundf;
    private javax.swing.JButton calculationButton;
    private javax.swing.JLabel homeLink;
    private javax.swing.JLabel issueLink;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JPanel leftMenu12;
    private javax.swing.JLabel logoutLink;
    private javax.swing.JPanel rightMenu;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel smLink;
    private javax.swing.JLabel taskLink;
    // End of variables declaration//GEN-END:variables
}
