/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;


import Users.FileOperation;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AccountWallet extends javax.swing.JFrame {

    /**
     * Creates new form AccountWallet
     */
    private String email;
    
    public AccountWallet() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void setEmail(String email) {
        this.email = email;
        System.out.println(getEmail());
        generateTable();
    }
    
    public String getEmail() {
        return email;
    }
    
    public void generateTable() {
        String columns[] = {"Date", "Transaction Details", "Amount"};
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
         
        FileOperation file = new FileOperation();
        file.setFile("resources/database/reloadHistory.txt");
        file.checkFilePath();
        file.retrieveData();
        ArrayList<String> records = file.getRetrievedData();
        
        DecimalFormat df = new DecimalFormat("RM0.00");
        
        for(String row : records) {
            String[] details = row.split(",");
            
            String rid = details[0];
            String emailFromFile = details[1];
            String dateFromFile = details[2];
            String amountFromFile = details[3];
            
            if(emailFromFile.equals(getEmail())) {
                double amount = Double.parseDouble(amountFromFile);
                String formattedAmount = df.format(amount);
                model.addRow(new Object[] {dateFromFile, "Reload Wallet", formattedAmount});
            }
        }
         transactionTable.setModel(model);
    }
    
    public void checkBalance() {
        FileOperation file = new FileOperation();
        file.setFile("resources/database/wallet.txt");
        file.checkFilePath();
        file.retrieveData();
        ArrayList<String> records = file.getRetrievedData();
        
        for(String row : records) {
            String[] details = row.split(",");
            
            String emailFromFile = details[0];
            double balanceFromFile = Double.parseDouble(details[1]);
            
            if(emailFromFile.equals(getEmail())) {
                creditLabel.setText(String.format("%.2f", balanceFromFile));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        walletLabel = new javax.swing.JLabel();
        walletIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        creditLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        homeNavi = new javax.swing.JLabel();
        reloadNavi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        showBalanceButton = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 246, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));

        walletLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        walletLabel.setText("My Wallet");

        walletIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/wallet-3.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("RM");

        creditLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        creditLabel.setText("****");

        jSeparator1.setBackground(new java.awt.Color(85, 85, 85));
        jSeparator1.setForeground(new java.awt.Color(85, 85, 85));

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(transactionTable);

        homeNavi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/home.png"))); // NOI18N
        homeNavi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeNavi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeNaviMouseClicked(evt);
            }
        });

        reloadNavi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/card.png"))); // NOI18N
        reloadNavi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reloadNavi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadNaviMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Top-Up Transaction History");

        showBalanceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/eye.png"))); // NOI18N
        showBalanceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showBalanceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showBalanceButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(6, 6, 6)
                            .addComponent(creditLabel))
                        .addComponent(jSeparator1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(walletLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                    .addComponent(showBalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(walletIcon))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(reloadNavi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(homeNavi))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(walletLabel)
                    .addComponent(homeNavi)
                    .addComponent(reloadNavi)
                    .addComponent(showBalanceButton))
                .addGap(12, 12, 12)
                .addComponent(walletIcon)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(creditLabel))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeNaviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeNaviMouseClicked
        Dashboard db = new Dashboard();
        db.setSessionEmail(getEmail());
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeNaviMouseClicked

    private void reloadNaviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadNaviMouseClicked
        ReloadCredit rc = new ReloadCredit();
        rc.setSessionEmail(getEmail());
        rc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reloadNaviMouseClicked

    private void showBalanceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showBalanceButtonMouseClicked
        checkBalance();
    }//GEN-LAST:event_showBalanceButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountWallet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creditLabel;
    private javax.swing.JLabel homeNavi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel reloadNavi;
    private javax.swing.JLabel showBalanceButton;
    private javax.swing.JTable transactionTable;
    private javax.swing.JLabel walletIcon;
    private javax.swing.JLabel walletLabel;
    // End of variables declaration//GEN-END:variables
}
