/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import Users.LoginPage;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private String email;
    
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void setSessionEmail(String email) {
        this.email = email;
        userLabel.setText(email);
    }
    
    public String getEmail() {
        return email;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        leftMenu = new javax.swing.JPanel();
        homeNaviLabel = new javax.swing.JLabel();
        bookHallLink = new javax.swing.JLabel();
        checkReservationLink = new javax.swing.JLabel();
        feedbackLink = new javax.swing.JLabel();
        companyLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        homeNaviIcon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bookHallicon = new javax.swing.JLabel();
        checkReservationIcon = new javax.swing.JLabel();
        contactUsIcon = new javax.swing.JLabel();
        refundIcon = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        pfpManagementIcon = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        refundLink = new javax.swing.JLabel();
        pfpManagementLink = new javax.swing.JLabel();
        exitLink = new javax.swing.JLabel();
        rightMenu = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        hallReservation = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        checkReservation = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cancelReservation = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        exitProgram = new javax.swing.JLabel();
        financial = new javax.swing.JLabel();
        paymentHistoryPanel = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        wallet = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        feedbackPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(248, 246, 240));
        background.setPreferredSize(new java.awt.Dimension(980, 620));

        leftMenu.setBackground(new java.awt.Color(172, 225, 199));
        leftMenu.setPreferredSize(new java.awt.Dimension(220, 620));

        homeNaviLabel.setText("Home Page");
        homeNaviLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bookHallLink.setText("Book Hall");
        bookHallLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookHallLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookHallLinkMouseClicked(evt);
            }
        });

        checkReservationLink.setText("Check Reserved Hall");
        checkReservationLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkReservationLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkReservationLinkMouseClicked(evt);
            }
        });

        feedbackLink.setText("Contact Us");
        feedbackLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        feedbackLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackLinkMouseClicked(evt);
            }
        });

        companyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/city-hall-small.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Hall Symphony Inc.");

        userLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userLabel.setText("hongjx0321@gmail.com");

        jSeparator1.setPreferredSize(new java.awt.Dimension(65, 10));

        homeNaviIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/home.png"))); // NOI18N
        homeNaviIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("General");

        bookHallicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/rent.png"))); // NOI18N
        bookHallicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        checkReservationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/check-up.png"))); // NOI18N
        checkReservationIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        contactUsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/help.png"))); // NOI18N
        contactUsIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        refundIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/refund.png"))); // NOI18N
        refundIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/logout.png"))); // NOI18N
        exitIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pfpManagementIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/user.png"))); // NOI18N
        pfpManagementIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Settings and Others");

        refundLink.setText("Hall Cancellation");
        refundLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refundLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refundLinkMouseClicked(evt);
            }
        });

        pfpManagementLink.setText("Profile Management");
        pfpManagementLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pfpManagementLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfpManagementLinkMouseClicked(evt);
            }
        });

        exitLink.setText("Log Out");
        exitLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout leftMenuLayout = new javax.swing.GroupLayout(leftMenu);
        leftMenu.setLayout(leftMenuLayout);
        leftMenuLayout.setHorizontalGroup(
            leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addComponent(contactUsIcon)
                        .addGap(18, 18, 18)
                        .addComponent(feedbackLink))
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addComponent(pfpManagementIcon)
                        .addGap(18, 18, 18)
                        .addComponent(pfpManagementLink))
                    .addComponent(jLabel16)
                    .addComponent(companyLogo)
                    .addComponent(jLabel2)
                    .addComponent(userLabel)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addComponent(homeNaviIcon)
                        .addGap(18, 18, 18)
                        .addComponent(homeNaviLabel))
                    .addComponent(jLabel8)
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addComponent(bookHallicon)
                        .addGap(18, 18, 18)
                        .addComponent(bookHallLink))
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addComponent(checkReservationIcon)
                        .addGap(18, 18, 18)
                        .addComponent(checkReservationLink))
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addComponent(refundIcon)
                        .addGap(18, 18, 18)
                        .addComponent(refundLink))
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addComponent(exitIcon)
                        .addGap(18, 18, 18)
                        .addComponent(exitLink)))
                .addGap(28, 28, 28))
        );
        leftMenuLayout.setVerticalGroup(
            leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addComponent(companyLogo)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addComponent(userLabel)
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(homeNaviIcon))
                    .addComponent(homeNaviLabel))
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addGap(13, 13, 13)
                .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookHallicon)
                    .addComponent(bookHallLink))
                .addGap(18, 18, 18)
                .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addComponent(checkReservationIcon)
                        .addGap(18, 18, 18)
                        .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refundIcon)
                            .addComponent(refundLink))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel16))
                    .addComponent(checkReservationLink))
                .addGap(18, 18, 18)
                .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addComponent(pfpManagementIcon)
                        .addGap(18, 18, 18)
                        .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactUsIcon)
                            .addComponent(feedbackLink))
                        .addGap(18, 18, 18)
                        .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitIcon)
                            .addComponent(exitLink)))
                    .addComponent(pfpManagementLink))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        rightMenu.setBackground(new java.awt.Color(248, 246, 240));
        rightMenu.setPreferredSize(new java.awt.Dimension(760, 620));

        dashboard.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dashboard.setText("Dashboard");

        hallReservation.setBackground(new java.awt.Color(255, 255, 255));
        hallReservation.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        hallReservation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hallReservation.setPreferredSize(new java.awt.Dimension(200, 150));
        hallReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hallReservationMouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/booking.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 51));
        jLabel21.setText("Hall Reservation");

        javax.swing.GroupLayout hallReservationLayout = new javax.swing.GroupLayout(hallReservation);
        hallReservation.setLayout(hallReservationLayout);
        hallReservationLayout.setHorizontalGroup(
            hallReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hallReservationLayout.createSequentialGroup()
                .addGroup(hallReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hallReservationLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel20))
                    .addGroup(hallReservationLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel21)))
                .addGap(31, 31, 31))
        );
        hallReservationLayout.setVerticalGroup(
            hallReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hallReservationLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        checkReservation.setBackground(new java.awt.Color(255, 255, 255));
        checkReservation.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        checkReservation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkReservation.setPreferredSize(new java.awt.Dimension(200, 150));
        checkReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkReservationMouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/choose.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 255));
        jLabel23.setText("Check Reservation");

        javax.swing.GroupLayout checkReservationLayout = new javax.swing.GroupLayout(checkReservation);
        checkReservation.setLayout(checkReservationLayout);
        checkReservationLayout.setHorizontalGroup(
            checkReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkReservationLayout.createSequentialGroup()
                .addGroup(checkReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkReservationLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel22))
                    .addGroup(checkReservationLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel23)))
                .addGap(59, 59, 59))
        );
        checkReservationLayout.setVerticalGroup(
            checkReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkReservationLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cancelReservation.setBackground(new java.awt.Color(255, 255, 255));
        cancelReservation.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        cancelReservation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelReservation.setPreferredSize(new java.awt.Dimension(200, 150));
        cancelReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelReservationMouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/cancel.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 51, 51));
        jLabel25.setText("Cancel Reservation");

        javax.swing.GroupLayout cancelReservationLayout = new javax.swing.GroupLayout(cancelReservation);
        cancelReservation.setLayout(cancelReservationLayout);
        cancelReservationLayout.setHorizontalGroup(
            cancelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelReservationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(63, 63, 63))
            .addGroup(cancelReservationLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel25)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        cancelReservationLayout.setVerticalGroup(
            cancelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelReservationLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        exitProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/delete.png"))); // NOI18N
        exitProgram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitProgramMouseClicked(evt);
            }
        });

        financial.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        financial.setText("Financial & Others");

        paymentHistoryPanel.setBackground(new java.awt.Color(255, 255, 255));
        paymentHistoryPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        paymentHistoryPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentHistoryPanel.setPreferredSize(new java.awt.Dimension(200, 150));
        paymentHistoryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentHistoryPanelMouseClicked(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/bill.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Payment History");

        javax.swing.GroupLayout paymentHistoryPanelLayout = new javax.swing.GroupLayout(paymentHistoryPanel);
        paymentHistoryPanel.setLayout(paymentHistoryPanelLayout);
        paymentHistoryPanelLayout.setHorizontalGroup(
            paymentHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentHistoryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(63, 63, 63))
            .addGroup(paymentHistoryPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        paymentHistoryPanelLayout.setVerticalGroup(
            paymentHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentHistoryPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        wallet.setBackground(new java.awt.Color(255, 255, 255));
        wallet.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        wallet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wallet.setPreferredSize(new java.awt.Dimension(200, 150));
        wallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                walletMouseClicked(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/wallet.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 204, 51));
        jLabel27.setText("My Wallet");

        javax.swing.GroupLayout walletLayout = new javax.swing.GroupLayout(wallet);
        wallet.setLayout(walletLayout);
        walletLayout.setHorizontalGroup(
            walletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walletLayout.createSequentialGroup()
                .addGroup(walletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(walletLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel26))
                    .addGroup(walletLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel27)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        walletLayout.setVerticalGroup(
            walletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walletLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        feedbackPanel.setBackground(new java.awt.Color(255, 255, 255));
        feedbackPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        feedbackPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackPanelMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/feedback.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Contact Us");

        javax.swing.GroupLayout feedbackPanelLayout = new javax.swing.GroupLayout(feedbackPanel);
        feedbackPanel.setLayout(feedbackPanelLayout);
        feedbackPanelLayout.setHorizontalGroup(
            feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(51, 51, 51))
        );
        feedbackPanelLayout.setVerticalGroup(
            feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rightMenuLayout = new javax.swing.GroupLayout(rightMenu);
        rightMenu.setLayout(rightMenuLayout);
        rightMenuLayout.setHorizontalGroup(
            rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitProgram)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightMenuLayout.createSequentialGroup()
                .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rightMenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dashboard))
                    .addGroup(rightMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(financial))
                    .addGroup(rightMenuLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hallReservation, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(feedbackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightMenuLayout.createSequentialGroup()
                                .addComponent(wallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(paymentHistoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightMenuLayout.createSequentialGroup()
                                .addComponent(checkReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(cancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(48, 48, 48))
        );
        rightMenuLayout.setVerticalGroup(
            rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitProgram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboard)
                .addGap(18, 18, 18)
                .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hallReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(financial)
                .addGap(18, 18, 18)
                .addGroup(rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paymentHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(wallet, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(feedbackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(leftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitProgramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitProgramMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitProgramMouseClicked

    private void hallReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hallReservationMouseClicked
        BookHall bookHall = new BookHall();
        bookHall.setEmail(getEmail());
        bookHall.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hallReservationMouseClicked

    private void walletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseClicked
        AccountWallet wallet = new AccountWallet();
        wallet.setVisible(true);
        wallet.setEmail(getEmail());
        this.dispose();
    }//GEN-LAST:event_walletMouseClicked

    private void checkReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkReservationMouseClicked
        CheckReservation reservation = new CheckReservation();
        reservation.setVisible(true);
        reservation.setEmail(userLabel.getText());
        this.dispose();
    }//GEN-LAST:event_checkReservationMouseClicked

    private void cancelReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelReservationMouseClicked
        CancelReservation cancellation = new CancelReservation();
        cancellation.setVisible(true);
        cancellation.setEmail(getEmail());
        this.dispose();
    }//GEN-LAST:event_cancelReservationMouseClicked

    private void paymentHistoryPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentHistoryPanelMouseClicked
        CheckPaymentHistory page = new CheckPaymentHistory();
        page.setEmail(getEmail());
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paymentHistoryPanelMouseClicked

    private void pfpManagementLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfpManagementLinkMouseClicked
       ProfileManagement pfp = new ProfileManagement();
       pfp.setEmail(getEmail());
       pfp.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_pfpManagementLinkMouseClicked

    private void bookHallLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookHallLinkMouseClicked
        BookHall bookHall = new BookHall();
        bookHall.setEmail(getEmail());
        bookHall.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bookHallLinkMouseClicked

    private void checkReservationLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkReservationLinkMouseClicked
        CheckReservation reservation = new CheckReservation();
        reservation.setVisible(true);
        reservation.setEmail(userLabel.getText());
        this.dispose();
    }//GEN-LAST:event_checkReservationLinkMouseClicked

    private void refundLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refundLinkMouseClicked
        CancelReservation cancellation = new CancelReservation();
        cancellation.setVisible(true);
        cancellation.setEmail(getEmail());
        this.dispose();
    }//GEN-LAST:event_refundLinkMouseClicked

    private void exitLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLinkMouseClicked
        JOptionPane.showMessageDialog(null, "You have successfully logout from your account!");
        LoginPage login = new LoginPage();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitLinkMouseClicked

    private void feedbackPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackPanelMouseClicked
        Feedback feedback = new Feedback();
        feedback.setEmail(getEmail());
        feedback.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_feedbackPanelMouseClicked

    private void feedbackLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackLinkMouseClicked
        Feedback feedback = new Feedback();
        feedback.setEmail(getEmail());
        feedback.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_feedbackLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel bookHallLink;
    private javax.swing.JLabel bookHallicon;
    private javax.swing.JPanel cancelReservation;
    private javax.swing.JPanel checkReservation;
    private javax.swing.JLabel checkReservationIcon;
    private javax.swing.JLabel checkReservationLink;
    private javax.swing.JLabel companyLogo;
    private javax.swing.JLabel contactUsIcon;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel exitLink;
    private javax.swing.JLabel exitProgram;
    private javax.swing.JLabel feedbackLink;
    private javax.swing.JPanel feedbackPanel;
    private javax.swing.JLabel financial;
    private javax.swing.JPanel hallReservation;
    private javax.swing.JLabel homeNaviIcon;
    private javax.swing.JLabel homeNaviLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel leftMenu;
    private javax.swing.JPanel paymentHistoryPanel;
    private javax.swing.JLabel pfpManagementIcon;
    private javax.swing.JLabel pfpManagementLink;
    private javax.swing.JLabel refundIcon;
    private javax.swing.JLabel refundLink;
    private javax.swing.JPanel rightMenu;
    private javax.swing.JLabel userLabel;
    private javax.swing.JPanel wallet;
    // End of variables declaration//GEN-END:variables
}
