/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import Users.FeedbackAndMessage;
import Users.FileOperation;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Feedback extends javax.swing.JFrame {

    /**
     * Creates new form Feedback
     */
    protected String email;
    
    public void setEmail(String email) {
        this.email = email;
        userEmail.setText(email);
        setEventID();
    }
    
    public String getEmail() {
        return email;
    }
    
    public void setEventID() {
        FileOperation file = new FileOperation();
        file.setFile("resources/database/reservation.txt");
        file.checkFilePath();
        file.retrieveData();
        
        ArrayList<String> records = file.getRetrievedData();
        for(String data : records) {
            String[] row = data.split(",");
            
            String reservationID = row[0];
            String emailFromFile = row[9];
            
            if(emailFromFile.equals(getEmail())) {
                eventBox.addItem(reservationID);
            }
        }
    }
    
    public Feedback() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    class InputOperation {
        protected String fullname;
        protected String chosenEvent;
        protected String userMessage;
        protected boolean validatedInput = false;
        
        public void setUserInput() {
            fullname = nameField.getText().trim();
            chosenEvent = (String) eventBox.getSelectedItem();
            userMessage = messageField.getText().trim();
        }
        
        public void validateUserInput() {
            if(fullname.isEmpty() || chosenEvent == null || userMessage.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please complete all required fields before sending feedback!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            } else {
                validatedInput = true;
            }
        }
        
        public void sendFeedback() {
            if(validatedInput) {
                FileOperation file = new FileOperation();
                file.setFile("resources/database/customerFeedback.txt");
                file.retrieveData();
                file.setSplitElement("F");
                file.IdOperation();
                int newID = file.getIdNum();
                String newFeedbackID = "F" + newID;
                
                System.out.println(newFeedbackID + "," + chosenEvent + "," + getEmail() + "," + fullname + "," + userMessage);
                
                FeedbackAndMessage feedback = new FeedbackAndMessage();
                FeedbackAndMessage.Customer customerFeedback = feedback.new Customer(
                    newFeedbackID,
                    chosenEvent, 
                    getEmail(),
                    fullname,
                    userMessage
                );
                
                String feedbackStatus = customerFeedback.getCustomerFeedback();
                
                if(feedbackStatus.equals("sent")) {
                    JOptionPane.showMessageDialog(null, "Feedback has been send to the manager successfully!", "Feedback Sent", JOptionPane.INFORMATION_MESSAGE);
                    customerFeedback.provideFeedback();
                } else {
                    JOptionPane.showMessageDialog(null, "Feedback cancelled!", "Action Paused", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        pageTitle = new javax.swing.JLabel();
        pageDescription = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        lineSeperator = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        eventBox = new javax.swing.JComboBox<>();
        nameField = new javax.swing.JTextField();
        nameTitle = new javax.swing.JLabel();
        eventTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageField = new javax.swing.JTextArea();
        messageTitle = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(248, 246, 240));

        pageTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pageTitle.setForeground(new java.awt.Color(0, 153, 255));
        pageTitle.setText("Feedback Survey");

        pageDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pageDescription.setText("Share your thoughts and suggestions to help us improve our services.");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/mail.png"))); // NOI18N

        userEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        userEmail.setText("Email Here");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/person.png"))); // NOI18N

        eventBox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        nameField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        nameTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        nameTitle.setText("Full Name:");

        eventTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        eventTitle.setText("Select an Event");

        messageField.setColumns(20);
        messageField.setRows(5);
        jScrollPane1.setViewportView(messageField);

        messageTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        messageTitle.setText("Message:");

        sendButton.setBackground(new java.awt.Color(0, 153, 255));
        sendButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setText("SEND MESSAGE");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(backgroundLayout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(backgroundLayout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addComponent(logo))
                                .addComponent(pageTitle)))
                        .addComponent(pageDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lineSeperator)
                        .addGroup(backgroundLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(userEmail))
                        .addGroup(backgroundLayout.createSequentialGroup()
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameTitle))
                            .addGap(18, 18, 18)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eventBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eventTitle))))
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sendButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(pageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageDescription)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(userEmail))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTitle)
                    .addComponent(eventTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        InputOperation operation = new InputOperation();
        operation.setUserInput();
        operation.validateUserInput();
        operation.sendFeedback();
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> eventBox;
    private javax.swing.JLabel eventTitle;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator lineSeperator;
    private javax.swing.JLabel logo;
    private javax.swing.JTextArea messageField;
    private javax.swing.JLabel messageTitle;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameTitle;
    private javax.swing.JLabel pageDescription;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel userEmail;
    // End of variables declaration//GEN-END:variables
}
