/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Scheduler;

import Users.FileOperation;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class EditHall extends javax.swing.JFrame {
    private String currentHallId;
    String[] fields2;

    private String email;
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getEmail() {
        return email;
    }
    
    public EditHall(String hallId) {
        this.setLocationRelativeTo(null);
        this.currentHallId = hallId;
        System.out.println(this.currentHallId);
        initComponents();
        loadHallData();
    }
    private void loadHallData() {
        FileOperation fileOp = new FileOperation();
        fileOp.setFile("resources/database/hall.txt");
        fileOp.setSplitElement(","); // Set the delimiter if needed

        String hallRecord = fileOp.getHallById(currentHallId);
        if (hallRecord != null) {
            // Assuming the fields are in order and you have corresponding JTextFields
            String[] fields = hallRecord.split(",");
            fields2 = fields;
            hallName.setText(fields[0]);
            hallTypeComboBox.setSelectedItem(fields[1]);
            openingTimeField.setText(fields[4]);
            closingTimeField.setText(fields[5]);
        } else {
            JOptionPane.showMessageDialog(this, "Hall ID not found.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        hallName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hallTypeComboBox = new javax.swing.JComboBox<>();
        priceField = new javax.swing.JLabel();
        EditHall = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        openingTimeField = new javax.swing.JTextField();
        closingTimeField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        terminateButton1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 246, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 520));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel11.setText("Hall Name");

        hallName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setText("Hall Type");

        hallTypeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        hallTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auditorium", "Banquet Hall", "Meeting Room" }));
        hallTypeComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        priceField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        priceField.setText("Hall Operation Section");

        EditHall.setBackground(new java.awt.Color(85, 85, 85));
        EditHall.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        EditHall.setForeground(new java.awt.Color(255, 255, 255));
        EditHall.setText("Edit Hall");
        EditHall.setBorder(null);
        EditHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditHallActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel12.setText("Hall Opening Time");

        openingTimeField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        closingTimeField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel13.setText("Hall Closing Time");

        jPanel2.setBackground(new java.awt.Color(172, 225, 199));

        terminateButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/delete.png"))); // NOI18N
        terminateButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        terminateButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terminateButton1MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("HALL MODIFICATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(terminateButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(terminateButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(priceField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hallName, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(hallTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditHall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(186, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hallName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(hallTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(priceField)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(openingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(EditHall, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditHallActionPerformed
                                          
    String hallId = hallName.getText().trim();
    String hallType = hallTypeComboBox.getSelectedItem().toString();
    boolean availability = true;
    int price=0;
    int capacity=0;
    switch (hallType) {
        case "Auditorium":
            price = 300;
            capacity = 1000;// Example price for Auditorium
            break;
        case "Banquet Hall":
            price = 100;
            capacity = 300;// Example price for Banquet Hall
            break;
        case "Meeting Room":
            price = 50; 
            capacity = 30;// Example price for Meeting Room
            break;
    }
    int openingTime = Integer.parseInt(openingTimeField.getText().trim());
    int closingTime = Integer.parseInt(closingTimeField.getText().trim());
    boolean maintenanceStatus = false;
    String maintenanceStartDate = null;
    String maintenanceEndDate = null;

    // Create a new Hall object
    Hall newHall = new Hall(hallId, hallType, price, capacity, openingTime, closingTime, 
                            availability,maintenanceStatus, maintenanceStartDate, maintenanceEndDate);

    // Add the hall using HallManager
        HallManagement manager = new HallFileOperation(); // You may need to initialize this properly
        manager.editHall(currentHallId,newHall);

    // Optionally, you can provide feedback to the user
        JOptionPane.showMessageDialog(this, "Hall edited successfully!");

    }//GEN-LAST:event_EditHallActionPerformed

    private void terminateButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminateButton1MouseClicked
        SchedulerDashboard dashboard = new SchedulerDashboard();
        dashboard.setEmail(getEmail());
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_terminateButton1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditHall;
    private javax.swing.JTextField closingTimeField;
    private javax.swing.JTextField hallName;
    private javax.swing.JComboBox<String> hallTypeComboBox;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField openingTimeField;
    private javax.swing.JLabel priceField;
    private javax.swing.JLabel terminateButton1;
    // End of variables declaration//GEN-END:variables
}
