/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Scheduler;

import Users.FileOperation;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class HandleTask extends javax.swing.JFrame {

    /**
     * Creates new form HandleTask
     */
    private String email;
    
    public void setEmail(String email) {
        this.email = email;
        generateTable();
    }
    
    public String getEmail() {
        return email;
    }
    
    public HandleTask() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void generateTable() {
        String columns[] = {"Email", "Hall ID", "Hall Type", "Due Date", "Remarks", "Status"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        FileOperation file = new FileOperation();
        file.setFile("resources/database/schedulerTask.txt");
        file.checkFilePath();
        file.retrieveData();

        ArrayList<String> scheduleRecords = file.getRetrievedData();
        for (String record : scheduleRecords) {
            String[] details = record.split(",");
            String emailFromFile = details[0];
            String hallID = details[1];
            String hallType = details[2];
            String date = details[3];
            String remarks = details[4];
            String status = details[5];
            
            if(emailFromFile.equals(getEmail())) {
                model.addRow(new Object[]{emailFromFile, hallID, hallType, date, remarks, status});
            }
        }

        taskTable.setModel(model);
    }
    
    private ArrayList<String> collectAllData() {
        ArrayList<String> allData = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) taskTable.getModel();

        for (int row = 0; row < model.getRowCount(); row++) {
            StringBuilder record = new StringBuilder();

            for (int col = 0; col < model.getColumnCount(); col++) {
                record.append(model.getValueAt(row, col)).append(",");
            }

            if (record.length() > 0) {
                record.setLength(record.length() - 1);
            }
            allData.add(record.toString());
        }

        return allData;
    }
    
    private void updateSelectedRow() {
        DefaultTableModel model = (DefaultTableModel) taskTable.getModel();
        int selectedRow = taskTable.getSelectedRow();

        if (selectedRow != -1) {
            String Email = emailLabel.getText();
            String HallID = idLabel.getText();
            String HallType = halltypeLabel.getText();
            String date = dateLabel.getText();
            String description = descriptionLabel.getText();
            String status = (String) statusComboBox.getSelectedItem();

            model.setValueAt(Email, selectedRow, 0);
            model.setValueAt(HallID, selectedRow, 1);
            model.setValueAt(HallType, selectedRow, 2);
            model.setValueAt(date, selectedRow, 3);
            model.setValueAt(description, selectedRow, 4);
            model.setValueAt(status, selectedRow, 5);
        }
    }

    public void saveAllChanges() {
        updateSelectedRow(); 
        ArrayList<String> updatedTableData = collectAllData();

        // Retrieve the existing data from the file
        FileOperation fileHandler = new FileOperation();
        fileHandler.setFile("resources/database/schedulerTask.txt");
        fileHandler.checkFilePath();
        fileHandler.retrieveData();
        ArrayList<String> taskRecords = fileHandler.getRetrievedData();

        for (int i = 0; i < taskRecords.size(); i++) {
            String[] fileRecord = taskRecords.get(i).split(",");
            String fileHallID = fileRecord[1]; 

            for (String updatedRecord : updatedTableData) {
                String[] tableRecord = updatedRecord.split(",");
                String tableHallID = tableRecord[1]; 


                if (fileHallID.equals(tableHallID)) {
                    taskRecords.set(i, updatedRecord); 
                    break; 
                }
            }
        }

        // Save the updated data back into the file
        fileHandler.updateData(taskRecords);

        JOptionPane.showMessageDialog(null, "Scheduler data updated successfully!");
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        terminateButton1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        tableTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();
        taskProgressionTitle = new javax.swing.JLabel();
        emailTitle = new javax.swing.JLabel();
        hallTitle = new javax.swing.JLabel();
        htTitle = new javax.swing.JLabel();
        duedateTitle = new javax.swing.JLabel();
        descriptionTitle = new javax.swing.JLabel();
        statusTitle = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        halltypeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 620));
        setPreferredSize(new java.awt.Dimension(720, 520));

        background.setBackground(new java.awt.Color(248, 246, 240));
        background.setMinimumSize(new java.awt.Dimension(980, 620));
        background.setPreferredSize(new java.awt.Dimension(980, 620));

        header.setBackground(new java.awt.Color(172, 225, 199));

        terminateButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/delete.png"))); // NOI18N
        terminateButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        terminateButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terminateButton1MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Task Management Dashboard");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(terminateButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(terminateButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        footer.setBackground(new java.awt.Color(248, 246, 240));

        tableTitle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tableTitle.setText("Overview of Task Management Table");

        taskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        taskTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taskTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taskTable);

        taskProgressionTitle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        taskProgressionTitle.setText("Update Task Progression");

        emailTitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        emailTitle.setText("Email :");

        hallTitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        hallTitle.setText("Hall ID : ");

        htTitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        htTitle.setText("Hall Type : ");

        duedateTitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        duedateTitle.setText("Due Date :");

        descriptionTitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        descriptionTitle.setText("Description :");

        statusTitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        statusTitle.setText("Update Status : ");

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        emailLabel.setText("Email Here");

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        idLabel.setText("Hall ID");

        halltypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        halltypeLabel.setText("Type");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        dateLabel.setText("Due date");

        descriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        descriptionLabel.setText("Task description");

        statusComboBox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "In Progress", "Completed" }));

        updateButton.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        updateButton.setText("Update Status");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableTitle)
                    .addGroup(footerLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(taskProgressionTitle)
                            .addGroup(footerLayout.createSequentialGroup()
                                .addComponent(emailTitle)
                                .addGap(18, 18, 18)
                                .addComponent(emailLabel))
                            .addGroup(footerLayout.createSequentialGroup()
                                .addComponent(hallTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idLabel))
                            .addGroup(footerLayout.createSequentialGroup()
                                .addComponent(htTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(halltypeLabel))
                            .addGroup(footerLayout.createSequentialGroup()
                                .addComponent(duedateTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateLabel))
                            .addGroup(footerLayout.createSequentialGroup()
                                .addComponent(descriptionTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(descriptionLabel))
                            .addGroup(footerLayout.createSequentialGroup()
                                .addComponent(statusTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tableTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(footerLayout.createSequentialGroup()
                        .addComponent(taskProgressionTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTitle)
                            .addComponent(emailLabel))
                        .addGap(18, 18, 18)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hallTitle)
                            .addComponent(idLabel))
                        .addGap(18, 18, 18)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(htTitle)
                            .addComponent(halltypeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(duedateTitle)
                            .addComponent(dateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptionTitle)
                            .addComponent(descriptionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusTitle)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminateButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminateButton1MouseClicked
        SchedulerDashboard dashboard = new SchedulerDashboard();
        dashboard.setVisible(true);
        dashboard.setEmail(getEmail());
        this.dispose();
    }//GEN-LAST:event_terminateButton1MouseClicked

    private void taskTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) taskTable.getModel();
        String Email = model.getValueAt(taskTable.getSelectedRow(),0).toString();
        String HallID = model.getValueAt(taskTable.getSelectedRow(),1).toString();
        String HallType = model.getValueAt(taskTable.getSelectedRow(),2).toString();
        String dateStr = model.getValueAt(taskTable.getSelectedRow(),3).toString();
        String Description = model.getValueAt(taskTable.getSelectedRow(),4).toString();
        String Status = model.getValueAt(taskTable.getSelectedRow(),5).toString();

        emailLabel.setText(Email);
        idLabel.setText(HallID);
        halltypeLabel.setText(HallType);
        dateLabel.setText(dateStr);
        descriptionLabel.setText(Description);
        statusComboBox.setSelectedItem(Status);
    }//GEN-LAST:event_taskTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        collectAllData();
        saveAllChanges();
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HandleTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HandleTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HandleTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HandleTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HandleTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel descriptionTitle;
    private javax.swing.JLabel duedateTitle;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailTitle;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel hallTitle;
    private javax.swing.JLabel halltypeLabel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel htTitle;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel statusTitle;
    private javax.swing.JLabel tableTitle;
    private javax.swing.JLabel taskProgressionTitle;
    private javax.swing.JTable taskTable;
    private javax.swing.JLabel terminateButton1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
