/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Scheduler;
import Users.FileOperation;
import Users.LoginPage;
import java.awt.GraphicsConfiguration;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */

public class SchedulerDashboard extends javax.swing.JFrame {
    static GraphicsConfiguration gc;
    /**
     * Creates new form Dashboard
     */
    private String email;
    
    public void setEmail(String email) {
        this.email = email;
        userLabel.setText(email);
    }
    
    public String getEmail() {
        return email;
    }
    
    
    public SchedulerDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        generateTable();
    }
    public void generateTable() {
        String columns[] = {"Hall ID", "Hall Type", "Price per Hour", "Hall Capacity"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        
        FileOperation file = new FileOperation();
        file.setFile("resources/database/hall.txt");
        file.checkFilePath();
        file.retrieveData();
        
        ArrayList<String> hallRecords = file.getRetrievedData();
        for(String record : hallRecords) {
            String[] details = record.split(",");
            String ID = details[0];
            String hallType = details[1];
            double hallPrice = Double.parseDouble(details[2]);
            int hallCapacity = Integer.parseInt(details[3]);
            
            model.addRow(new Object[]{ID, hallType, hallPrice, hallCapacity});
        }
        
        hallTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        companyLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        checkReservationLink = new javax.swing.JLabel();
        checkReservationIcon = new javax.swing.JLabel();
        checkReservationIcon1 = new javax.swing.JLabel();
        ViewReservation = new javax.swing.JLabel();
        exitLink = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        checkReservationIcon2 = new javax.swing.JLabel();
        taskManagementLink = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hallTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        EditHall = new javax.swing.JButton();
        clearButton1 = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        FilterButton = new javax.swing.JButton();
        clearFilterButton = new javax.swing.JButton();
        maintanenceCheck = new javax.swing.JCheckBox();
        hallTypeDropdown = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 220));

        jPanel1.setBackground(new java.awt.Color(248, 246, 240));
        jPanel1.setMinimumSize(new java.awt.Dimension(980, 620));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 620));

        jPanel2.setBackground(new java.awt.Color(172, 225, 199));
        jPanel2.setMinimumSize(new java.awt.Dimension(220, 620));
        jPanel2.setPreferredSize(new java.awt.Dimension(220, 620));

        companyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/city-hall-small.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Hall Symphony Inc.");

        userLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userLabel.setText("Email");

        jSeparator1.setPreferredSize(new java.awt.Dimension(65, 10));

        checkReservationLink.setText("Hall Listing");
        checkReservationLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkReservationLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkReservationLinkMouseClicked(evt);
            }
        });

        checkReservationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/check-up.png"))); // NOI18N
        checkReservationIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        checkReservationIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/check-up.png"))); // NOI18N
        checkReservationIcon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ViewReservation.setText("Bookings");
        ViewReservation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewReservationMouseClicked(evt);
            }
        });

        exitLink.setText("Log Out");
        exitLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLinkMouseClicked(evt);
            }
        });

        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/logout.png"))); // NOI18N
        exitIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        checkReservationIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_sources/images/check-up.png"))); // NOI18N
        checkReservationIcon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        taskManagementLink.setText("Task Management");
        taskManagementLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taskManagementLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taskManagementLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkReservationIcon2)
                        .addGap(18, 18, 18)
                        .addComponent(taskManagementLink))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(exitIcon)
                        .addGap(18, 18, 18)
                        .addComponent(exitLink))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkReservationIcon1)
                        .addGap(18, 18, 18)
                        .addComponent(ViewReservation))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkReservationIcon)
                        .addGap(18, 18, 18)
                        .addComponent(checkReservationLink))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(userLabel)
                        .addComponent(companyLogo)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(companyLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkReservationIcon)
                    .addComponent(checkReservationLink))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkReservationIcon1)
                    .addComponent(ViewReservation))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkReservationIcon2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitIcon)
                            .addComponent(exitLink)))
                    .addComponent(taskManagementLink))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(248, 246, 240));
        jPanel3.setMinimumSize(new java.awt.Dimension(760, 620));
        jPanel3.setPreferredSize(new java.awt.Dimension(760, 620));

        hallTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(hallTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Hall Listing");

        DeleteButton.setBackground(new java.awt.Color(85, 85, 85));
        DeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete Hall");
        DeleteButton.setBorder(null);
        DeleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        EditHall.setBackground(new java.awt.Color(85, 85, 85));
        EditHall.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        EditHall.setForeground(new java.awt.Color(255, 255, 255));
        EditHall.setText("Edit Hall");
        EditHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditHallActionPerformed(evt);
            }
        });

        clearButton1.setBackground(new java.awt.Color(85, 85, 85));
        clearButton1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        clearButton1.setForeground(new java.awt.Color(255, 255, 255));
        clearButton1.setText("Hall Maintanence");
        clearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton1ActionPerformed(evt);
            }
        });

        searchField.setText("Search Here...");

        FilterButton.setBackground(new java.awt.Color(85, 85, 85));
        FilterButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        FilterButton.setForeground(new java.awt.Color(255, 255, 255));
        FilterButton.setText("Find Now");
        FilterButton.setBorder(null);
        FilterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterButtonActionPerformed(evt);
            }
        });

        clearFilterButton.setBackground(new java.awt.Color(85, 85, 85));
        clearFilterButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        clearFilterButton.setForeground(new java.awt.Color(255, 255, 255));
        clearFilterButton.setText("Clear Filter");
        clearFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFilterButtonActionPerformed(evt);
            }
        });

        maintanenceCheck.setText("Maintanence");
        maintanenceCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintanenceCheckActionPerformed(evt);
            }
        });

        hallTypeDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Auditorium", "Banquet Hall", "Meeting Room" }));
        hallTypeDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallTypeDropdownActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Hall Type");

        AddButton.setBackground(new java.awt.Color(85, 85, 85));
        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add Hall");
        AddButton.setBorder(null);
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditHall, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clearButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FilterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearFilterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maintanenceCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hallTypeDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(maintanenceCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hallTypeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(FilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditHall, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkReservationLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkReservationLinkMouseClicked

    }//GEN-LAST:event_checkReservationLinkMouseClicked

    private void ViewReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewReservationMouseClicked

        ViewReservation reservationPage = new ViewReservation();
        reservationPage.setEmail(getEmail());
        reservationPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewReservationMouseClicked

    private void exitLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLinkMouseClicked
        LoginPage login = new LoginPage();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitLinkMouseClicked

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int selectedRow = hallTable.getSelectedRow();
    
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a hall to delete.");
            return;
        }

    // Assuming the table has a column for hall ID, e.g., column index 0
        String hallId = hallTable.getValueAt(selectedRow, 0).toString();

        // Create FileOperation object
        
        HallManagement manager = new HallFileOperation(); // You may need to initialize this properly
        manager.deleteHall(hallId);

        // Create a list to store updated records
        
        
        // Provide feedback to the user
        JOptionPane.showMessageDialog(this, "Hall deleted successfully.");
        generateTable();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void EditHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditHallActionPerformed
        int selectedRow = hallTable.getSelectedRow();
        if (selectedRow != -1) { // Check if a row is selected
            // Get the hall ID from the selected row
            String hallId = hallTable.getValueAt(selectedRow, 0).toString(); // Assuming ID is in the first column
            // Pass the hall ID to the new JFrame
                EditHall editHallFrame = new EditHall(hallId);
                editHallFrame.setVisible(true);
                editHallFrame.setEmail(getEmail());
                this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a hall to edit.");
        }
    }//GEN-LAST:event_EditHallActionPerformed

    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
        int selectedRow = hallTable.getSelectedRow();
        if (selectedRow != -1) { // Check if a row is selected
            // Get the hall ID from the selected row
            String hallId = hallTable.getValueAt(selectedRow, 0).toString(); // Assuming ID is in the first column
            // Pass the hall ID to the new JFrame
                MaintanenceHall maintanenceHallFrame = new MaintanenceHall(hallId);
                maintanenceHallFrame.setVisible(true);
                maintanenceHallFrame.setEmail(getEmail());
                this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a hall to edit."," hall id not found", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_clearButton1ActionPerformed

    private void FilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterButtonActionPerformed
        DefaultTableModel table = (DefaultTableModel) hallTable.getModel();
        table.setRowCount(0); // Clear existing rows

        // Get user search input and hall type
        String userSearch = searchField.getText().trim();
        String hallType = String.valueOf(hallTypeDropdown.getSelectedItem()).trim();
        boolean maintenanceCheckSelected = maintanenceCheck.isSelected();

        // Set file path and retrieve data
        FileOperation file = new FileOperation();
        file.setFile("resources/database/hall.txt");
        file.checkFilePath();
        file.retrieveData();

        ArrayList<String> hallRecords = file.getRetrievedData();
        boolean matchingResult = false;
        ArrayList<String> filteredHallRecord = new ArrayList<>();

        // Loop through hall records
        for (String record : hallRecords) {
            String[] row = record.split(",");

            // Assuming the row array structure is [id, type, price, capacity, ..., maintenanceStatus]
            String id = row[0];
            String type = row[1];
            String price = row[2];
            String capacity = row[3];
            boolean maintenanceStatus = Boolean.parseBoolean(row[7]); // Ensure maintenanceStatus is treated as boolean

            // Check if the hall type and search term match
            boolean typeMatches = hallType.equalsIgnoreCase("all") || type.equalsIgnoreCase(hallType);
            boolean searchMatches = userSearch.isEmpty() || record.toLowerCase().contains(userSearch.toLowerCase());
            boolean maintenanceMatches = !maintenanceCheckSelected || maintenanceStatus; 

            if (typeMatches && searchMatches && maintenanceMatches) {
                matchingResult = true;
                filteredHallRecord.add(record);

                // Add matching record to the table
                table.addRow(new Object[]{id, type, price, capacity});
            }
        }

        // Check if any matching records were found
        if (matchingResult) {
            JOptionPane.showMessageDialog(rootPane, "Record(s) Found!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Sorry, no records found.", "Record Not Found", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_FilterButtonActionPerformed

    private void clearFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFilterButtonActionPerformed
        generateTable();
    }//GEN-LAST:event_clearFilterButtonActionPerformed

    private void maintanenceCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintanenceCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintanenceCheckActionPerformed

    private void hallTypeDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallTypeDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hallTypeDropdownActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        AddHall addHall = new AddHall();
        addHall.setVisible(true);
        addHall.setEmail(getEmail());
        this.dispose();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void taskManagementLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskManagementLinkMouseClicked
        HandleTask task = new HandleTask();
        task.setEmail(getEmail());
        task.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_taskManagementLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchedulerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchedulerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchedulerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchedulerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchedulerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditHall;
    private javax.swing.JButton FilterButton;
    private javax.swing.JLabel ViewReservation;
    private javax.swing.JLabel checkReservationIcon;
    private javax.swing.JLabel checkReservationIcon1;
    private javax.swing.JLabel checkReservationIcon2;
    private javax.swing.JLabel checkReservationLink;
    private javax.swing.JButton clearButton1;
    private javax.swing.JButton clearFilterButton;
    private javax.swing.JLabel companyLogo;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel exitLink;
    private javax.swing.JTable hallTable;
    private javax.swing.JComboBox<String> hallTypeDropdown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox maintanenceCheck;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel taskManagementLink;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
